export default [
  // over 50 damage weapons
  [
    { name: "AWM", points: "-100" },
    { name: "Berreta686", points: "-100" },
    { name: "Crossbow", points: "-100" },
    { name: "DP28", points: "-51" },
    { name: "FNFal", points: "-58" },
    { name: "Kar98k", points: "-75" },
    { name: "M24", points: "-79" },
    { name: "Mk14", points: "-61" },
    { name: "Saiga12", points: "-100" },
    { name: "SKS", points: "-53" },
    { name: "Win1894", points: "-66" },
    { name: "NagantM1895", points: "-55" },
    { name: "Rhino", points: "-55" },
    { name: "Sawnoff", points: "-100" },
    { name: "Winchester", points: "-100" },
  ],
  // under 50 damage weapons
  [
    { name: "AK47", points: "-49" },
    { name: "AUG", points: "-43" },
    { name: "BerylM762", points: "-47" },
    { name: "Groza", points: "-49" },
    { name: "HK416", points: "-43" },
    { name: "M16A4", points: "-43" },
    { name: "M249", points: "-45" },
    { name: "Mini14", points: "-46" },
    { name: "Mk47Mutant", points: "-49" },
    { name: "QBU88", points: "-48" },
    { name: "QBZ95", points: "-43" },
    { name: "SCAR-L", points: "-43" },
    { name: "Thompson", points: "-40" },
    { name: "UMP", points: "-39" },
    { name: "UZI", points: "-26" },
    { name: "Vector", points: "-34" },
    { name: "VSS", points: "-41" },
    { name: "G18", points: "-23" },
    { name: "M9", points: "-35" },
    { name: "M1911", points: "-41" },
  ],
  // melee items
  [
    { name: "crowbar", points: "0" },
    { name: "machete", points: "0" },
    { name: "pan", points: "0" },
    { name: "sickle", points: "0" },
    { name: "Apple", points: "0" },
    { name: "Grenade", points: "0" },
    { name: "Molotov", points: "0" },
  ],
  // health items
  [
    { name: "ArmorLv1", points: "+30" },
    { name: "ArmorLv2", points: "+40" },
    { name: "ArmorLv3", points: "+55" },
    { name: "Bandage", points: "+10" },
    { name: "EnergyDrink", points: "+40" },
    { name: "FirstAid", points: "+75" },
    { name: "HeadLv1", points: "+30" },
    { name: "HeadLv2", points: "+40" },
    { name: "HeadLv3", points: "+55" },
    { name: "MedKit", points: "+100" },
    { name: "PainKiller", points: "+60" },
    { name: "Syringe", points: "+100" },
  ],
];
