export const seed = {
  isDataReady: true,
  vocabulary: [
    'apple',
    'apricot',
    'avocado',
    'banana',
    'bell pepper',
    'bilberry',
    'blackberry',
    'blackcurrant',
    'blood orange',
    'blueberry',
    'boysenberry',
    'breadfruit',
    'canary melon',
    'cantaloupe',
    'cherimoya',
    'cherry',
    'chili pepper',
  ],
  expressions: [
    'I like apple.',
    'I like apricot.',
    'I like avocado.',
    'I like banana.',
    'I like bell pepper.',
    'I like bilberry.',
    'I like blackberry.',
    'I like blackcurrant.',
    'I like blood orange.',
    'I like blueberry.',
    'I like boysenberry.',
    'I like breadfruit.',
    'I like canary melon.',
    'I like cantaloupe.',
    'I like cherimoya.',
    'I like cherry.',
    'I like chili pepper.',
  ],
};
