import React from 'react';
import SeoWrapper from 'components/SeoWrapper';
import { PageHeading, PageSubHeading } from 'components/PageHeadings';
import PageContent from 'components/PageContent';

export default function PrivacyPage() {
  return (
    <SeoWrapper
      title="Privacy Policy"
      description="Read our full privacy policy. We are committed to being transparent."
    >
      <PageHeading>Privacy Policy</PageHeading>
      <PageSubHeading>Last Updated: September 12, 2021</PageSubHeading>
      <PageSubHeading>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </PageSubHeading>
      <PageSubHeading>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy was created
        with the help of the{' '}
        <a
          href="https://www.termsfeed.com/privacy-policy-generator/"
          target="_blank"
        >
          Privacy Policy Generator
        </a>{' '}
        and edited to make additions and customize it.
      </PageSubHeading>

      <PageContent>
        <PageContent.Header>Interpretation and Definitions</PageContent.Header>
        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Interpretation
        </PageContent.Header>
        <PageContent.Text>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </PageContent.Text>
        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Definitions
        </PageContent.Header>
        <PageContent.Text>
          For the purposes of this Privacy Policy:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <PageContent.Text>
              <strong>Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
              in this Agreement) refers to ESL in the ROK.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Cookies</strong> are small files that are placed on Your
              computer, mobile device or any other device by a website,
              containing the details of Your browsing history on that website
              among its many uses.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Country</strong> refers to: British Columbia, Canada
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Service</strong> refers to the Website.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, to provide the Service on behalf of the
              Company, to perform services related to the Service or to assist
              the Company in analyzing how the Service is used.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Website</strong> refers to ESL in the ROK, accessible from{' '}
              <a
                href="https://www.eslintherok.com"
                rel="external nofollow noopener"
                target="_blank"
              >
                https://www.eslintherok.com
              </a>
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </PageContent.Text>
          </li>
        </PageContent.List>

        <PageContent.Header>
          Collecting and Using Your Personal Data
        </PageContent.Header>
        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Types of Data Collected
        </PageContent.Header>
        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Personal Data
        </PageContent.Header>
        <PageContent.Text>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <PageContent.Text>Email address</PageContent.Text>
          </li>
          <li>
            <PageContent.Text>Usage Data</PageContent.Text>
          </li>
        </PageContent.List>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Usage Data
        </PageContent.Header>
        <PageContent.Text>
          Usage Data is collected automatically when using the Service.
        </PageContent.Text>
        <PageContent.Text>
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </PageContent.Text>
        <PageContent.Text>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </PageContent.Text>
        <PageContent.Text>
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Tracking Technologies and Cookies
        </PageContent.Header>
        <PageContent.Text>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <strong>Cookies or Browser Cookies.</strong> A cookie is a small
            file placed on Your Device. You can instruct Your browser to refuse
            all Cookies or to indicate when a Cookie is being sent. However, if
            You do not accept Cookies, You may not be able to use some parts of
            our Service. Unless you have adjusted Your browser setting so that
            it will refuse Cookies, our Service may use Cookies.
          </li>
          <li>
            <strong>Flash Cookies.</strong> Certain features of our Service may
            use local stored objects (or Flash Cookies) to collect and store
            information about Your preferences or Your activity on our Service.
            Flash Cookies are not managed by the same browser settings as those
            used for Browser Cookies. For more information on how You can delete
            Flash Cookies, please read &quot;Where can I change the settings for
            disabling, or deleting local shared objects?&quot; available at{' '}
            <a
              href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
              rel="external nofollow noopener"
              target="_blank"
            >
              https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
            </a>
          </li>
          <li>
            <strong>Web Beacons.</strong> Certain sections of our Service and
            our emails may contain small electronic files known as web beacons
            (also referred to as clear gifs, pixel tags, and single-pixel gifs)
            that permit the Company, for example, to count users who have
            visited those pages or opened an email and for other related website
            statistics (for example, recording the popularity of a certain
            section and verifying system and server integrity).
          </li>
        </PageContent.List>
        <PageContent.Text>
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
          Persistent Cookies remain on Your personal computer or mobile device
          when You go offline, while Session Cookies are deleted as soon as You
          close Your web browser. You can learn more about cookies here:{' '}
          <a href="https://www.termsfeed.com/blog/cookies/" target="_blank">
            All About Cookies by TermsFeed
          </a>
          .
        </PageContent.Text>
        <PageContent.Text>
          We use Cookies for the purposes set out below:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <PageContent.Text>
              <strong>Necessary / Essential Cookies</strong>
            </PageContent.Text>
            <PageContent.Text>Type: Session Cookies</PageContent.Text>
            <PageContent.Text>Administered by: Us</PageContent.Text>
            <PageContent.Text>
              Purpose: These Cookies are essential to provide You with services
              available through the Website and to enable You to use some of its
              features. They help to authenticate users and prevent fraudulent
              use of user accounts. Without these Cookies, the services that You
              have asked for cannot be provided, and We only use these Cookies
              to provide You with those services.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Notice Acceptance Cookies</strong>
            </PageContent.Text>
            <PageContent.Text>Type: Persistent Cookies</PageContent.Text>
            <PageContent.Text>Administered by: Us</PageContent.Text>
            <PageContent.Text>
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>Analysis Cookies</strong>
            </PageContent.Text>
            <PageContent.Text>Type: Third Party Cookies</PageContent.Text>
            <PageContent.Text>
              Administered by: Google Analytics
            </PageContent.Text>
            <PageContent.Text>
              Purpose: These Cookies allow us to view and track how You interact
              with the Site. The purpose of these Cookies is to help us improve
              the Site, measure the popularity of games (like how many rounds
              are played), view pageview counts and how You are referred to the
              Site.
            </PageContent.Text>
          </li>
        </PageContent.List>
        <PageContent.Text>
          For more information about the cookies we use and your choices
          regarding cookies, please visit the Cookies section of our Privacy
          Policy below.
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Cookie Policy
        </PageContent.Header>
        <PageContent.Text>
          The following are first-party Cookies used on our Site set by Us:
        </PageContent.Text>
        <table>
          <tbody>
            <tr>
              <th>Cookie Name</th>
              <th>Default Expiration</th>
              <th>Description</th>
              <th>Service Provider</th>
            </tr>
            <tr>
              <td>callback-url</td>
              <td>session only</td>
              <td>Used to direct users after authentication.</td>
              <td>Us</td>
            </tr>
            <tr>
              <td>csrf-token</td>
              <td>session only</td>
              <td>Used to prevent cross-site forgery attacks.</td>
              <td>Us</td>
            </tr>
            <tr>
              <td>session-token</td>
              <td>14 days</td>
              <td>Used to authenticate a user</td>
              <td>Us</td>
            </tr>
          </tbody>
        </table>

        <PageContent.Text>
          The following are third-party Cookies used on our Site set by another
          service:
        </PageContent.Text>
        <table>
          <tbody>
            <tr>
              <th>Cookie Name</th>
              <th>Default Expiration</th>
              <th>Description</th>
              <th>Service Provider</th>
            </tr>
            <tr>
              <td>_ga</td>
              <td>2 years</td>
              <td>Used to distinguish users.</td>
              <td>Google Analytics</td>
            </tr>
            <tr>
              <td>_gid</td>
              <td>24 hours</td>
              <td>Used to distinguish users.</td>
              <td>Google Analytics</td>
            </tr>
            <tr>
              <td>_gat</td>
              <td>1 minute</td>
              <td>Used to throttle request rate.</td>
              <td>Google Analytics</td>
            </tr>
          </tbody>
        </table>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Use of Your Personal Data
        </PageContent.Header>
        <PageContent.Text>
          The Company may use Personal Data for the following purposes:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <PageContent.Text>
              <strong>To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>To manage Your Account:</strong> to manage Your
              registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a registered user.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>To contact You:</strong> To contact You by email regarding
              updates or informative communications related to functionalities,
              when necessary or reasonable for their implementation.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>For business transfers:</strong> We may use Your
              information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or
              transfer of some or all of Our assets, whether as a going concern
              or as part of bankruptcy, liquidation, or similar proceeding, in
              which Personal Data held by Us about our Service users is among
              the assets transferred.
            </PageContent.Text>
          </li>
          <li>
            <PageContent.Text>
              <strong>For other purposes</strong>: We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of new features and to
              evaluate and improve our Service and your experience.
            </PageContent.Text>
          </li>
        </PageContent.List>
        <PageContent.Text>
          We may share Your personal information in the following situations:
        </PageContent.Text>
        <PageContent.List>
          <li>
            <strong>With Service Providers:</strong> We may share Your personal
            information with Service Providers to monitor and analyze the use of
            our Service, to contact You.
          </li>
          <li>
            <strong>For business transfers:</strong> We may share or transfer
            Your personal information in connection with, or during negotiations
            of, any merger, sale of Company assets, financing, or acquisition of
            all or a portion of Our business to another company.
          </li>
          <li>
            <strong>With Affiliates:</strong> We may share Your information with
            Our affiliates, in which case we will require those affiliates to
            honor this Privacy Policy. Affiliates include Our parent company and
            any other subsidiaries, joint venture partners or other companies
            that We control or that are under common control with Us.
          </li>
          <li>
            <strong>With business partners:</strong> We may share Your
            information with Our business partners to offer You certain
            products, services or promotions.
          </li>
          <li>
            <strong>With other users:</strong> when You share personal
            information or otherwise interact in public areas with other users,
            such information may be viewed by all users and may be publicly
            distributed outside.
          </li>
          <li>
            <strong>With Your consent</strong>: We may disclose Your personal
            information for any other purpose with Your consent.
          </li>
        </PageContent.List>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Retention of Your Personal Data
        </PageContent.Header>
        <PageContent.Text>
          The Company will retain Your Personal Data for as long as your Account
          is active.
        </PageContent.Text>
        <PageContent.Text>
          The Company will delete inactive Accounts after a period of twelve
          (12) months.
        </PageContent.Text>
        <PageContent.Text>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Transfer of Your Personal Data
        </PageContent.Header>
        <PageContent.Text>
          Your information, including Personal Data, is processed in places
          where the parties involved in the processing are located. It means
          that this information may be transferred to — and maintained on —
          computers located outside of Your state, province, country or other
          governmental jurisdiction where the data protection laws may differ
          than those from Your jurisdiction.
        </PageContent.Text>
        <PageContent.Text>
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </PageContent.Text>
        <PageContent.Text>
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Disclosure of Your Personal Data
        </PageContent.Header>
        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Business Transactions
        </PageContent.Header>
        <PageContent.Text>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Law enforcement
        </PageContent.Header>
        <PageContent.Text>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </PageContent.Text>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1em',
            margin: '1.5rem 0 1rem',
          }}
        >
          Other legal requirements
        </PageContent.Header>
        <PageContent.Text>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </PageContent.Text>
        <PageContent.List>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            Protect the personal safety of Users of the Service or the public
          </li>
          <li>Protect against legal liability</li>
        </PageContent.List>

        <PageContent.Header
          style={{
            textDecoration: 'none',
            fontSize: '1.2em',
            marginTop: '2.5rem',
          }}
        >
          Security of Your Personal Data
        </PageContent.Header>
        <PageContent.Text>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </PageContent.Text>

        <PageContent.Header>Children's Privacy</PageContent.Header>
        <PageContent.Text>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
          If We become aware that We have collected Personal Data from anyone
          under the age of 13 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </PageContent.Text>

        <PageContent.Header>Links to Other Websites</PageContent.Header>
        <PageContent.Text>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the Privacy
          Policy of every site You visit.
        </PageContent.Text>
        <PageContent.Text>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </PageContent.Text>

        <PageContent.Header>Changes to this Privacy Policy</PageContent.Header>
        <PageContent.Text>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting an updated Privacy Policy on this page.
        </PageContent.Text>
        <PageContent.Text>
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last updated&quot; date at the top of this Privacy Policy.
        </PageContent.Text>
        <PageContent.Text>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </PageContent.Text>

        <PageContent.Header>Contact Us</PageContent.Header>
        <PageContent.Text>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </PageContent.Text>
        <PageContent.List>
          <li>
            By visiting this page on our website:{' '}
            <a
              href="https://www.eslintherok.com/contact"
              rel="external nofollow noopener"
              target="_blank"
            >
              https://www.eslintherok.com/contact
            </a>
          </li>
        </PageContent.List>
      </PageContent>

      <style jsx>{`
        table {
          font-size: 0.8em;
          text-align: center;
          border-spacing: 0px;
          border: 1px solid #04a7fbab;
        }
        table tr th,
        table tr td {
          border: 1px solid #04a7fbab;
          padding: 0.25rem;
          margin: 0;
        }

        th {
          background-color: #04a7fb26;
          line-height: 2;
        }

        td {
          background-color: #04a7fb0f;
          line-height: 1.5;
        }

        table tr th:nth-of-type(1),
        table tr td:nth-of-type(1) {
          width: 18%;
        }

        table tr th:nth-of-type(2),
        table tr td:nth-of-type(2) {
          width: 18%;
        }

        table tr th:nth-of-type(3),
        table tr td:nth-of-type(3) {
          width: 36%;
        }

        table tr th:nth-of-type(4),
        table tr td:nth-of-type(4) {
          width: 18%;
        }
      `}</style>
    </SeoWrapper>
  );
}
